### ISSUE TITLE
Remove PHP, Ruby, Java syntax docs from syntax page

### ISSUE THREAD

**Issue by michaelborn** [ortus-docs/Modern-ColdFusion-CFML-In-100-Minutes#14]
I don't understand why this is here - what do PHP, Ruby and Java have to do with CF tag or script syntax?

https://modern-cfml.ortusbooks.com/cfml-language/syntax

**Comment by michaelborn** [comment]
https://github.com/ortus-docs/Modern-ColdFusion-CFML-In-100-Minutes/blob/master/cfml-language/syntax.md

**Comment by lmajano** [comment]
The references to other languages where left to expand the point on syntax by providing the comparisons. Especially when people from other programming language backgrounds are learning CFML. 

Question:  why don’t you think it should be there?

**Comment by michaelborn** [comment]
I just don't think it makes sense to have a PHP or Ruby example in a CF tutorial. I wouldn't expect to see Javascript examples in a [Ruby tutorial](https://www.tutorialspoint.com/ruby/ruby_syntax.htm), for example.

I'll freely admit that this is my own opinion and I am not always right. :) At the very least (again, in my opinion), there should be an explanation of why the Ruby, PHP etc. samples are there. Hopefully that would prevent the examples from confusing people like me.

**Comment by lmajano** [comment]
Actually that's a good point 👏 . I will be updating that page to describe the reasoning behind the multiple language syntax references, which is missing.

Just for historical purposes:
>The intent is for developers from OTHER languages, to be able to comprehend the syntax differences and similarities.  Especially now a days where we live in a polyglot world where developers have to work with 2-5 different languages daily.

**Comment by lmajano** [comment]
I have updated the page: https://modern-cfml.ortusbooks.com/cfml-language/syntax

**Comment by michaelborn** [comment]
Thank you! That makes a lot more sense to me, and I love the wording. :)
